name: Python CI
on: [push, pull_request]

jobs:
  test-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - name: Setup and run ganache
      run: |
        docker run --detach --publish 8545:8545 --network-alias ganache -e DOCKER=true trufflesuite/ganache-cli:latest --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --noVMErrorsOnRPCResponse --chainId 1337 --networkId 1337 -d
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-test.txt') }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -r requirements-test.txt coveralls pre-commit
      env:
        PIP_USE_MIRRORS: true
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Run tests and coverage
      run: |
        flake8
        pytest -rxXs
        coverage run --source=$SOURCE_FOLDER -m py.test -rxXs
      env:
        SOURCE_FOLDER: safe_cli
    - name: Send results to coveralls
      if: ${{ env.COVERALLS_REPO_TOKEN }}
      run: |
        coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for coveralls
