name: Python CI
on: [push, pull_request]

jobs:
  test-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]
    steps:
    - name: Setup and run ganache
      run: docker run --detach --publish 8545:8545 --network-alias ganache -e DOCKER=true trufflesuite/ganache:latest --defaultBalanceEther 10000 --gasLimit 10000000 -a 30 --chain.chainId 1337 --chain.networkId 1337 -d
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'
    - name: Install dependencies
      run: |
        pip install wheel
        pip install -r requirements-test.txt coveralls pre-commit
      env:
        PIP_USE_MIRRORS: true
    - name: Run pre-commit
      run: pre-commit run --all-files
    - name: Run tests and coverage
      run: |
        flake8
        pytest -rxXs
        coverage run --source=$SOURCE_FOLDER -m py.test -rxXs
      env:
        SOURCE_FOLDER: safe_cli
    - name: Send results to coveralls
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for coveralls
  publish:
    runs-on: ubuntu-latest
    needs: test-app
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: 'requirements*.txt'
    - name: Deploy Package
      run: |
        python -m pip install --upgrade setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
